import React from "react";
import WalletAndClientProvider from "../wallet/WalletAndClientProvider";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import { ChakraProvider } from '@chakra-ui/react'
import Topbar from "@/components/topbar/Topbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <WalletAndClientProvider>
          <Topbar/>
          {children}</WalletAndClientProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
